version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  node-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: admin
      DB_DATABASE: test
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # REDIS_PASSWORD: your_redis_password # Uncomment and set if your Redis requires a password
    depends_on:
      - postgres
      - redis

volumes:
  redis:
    driver: local
  docker-postgres:
