version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  node-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: admin
      DB_DATABASE: test
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # REDIS_PASSWORD: your_redis_password # Uncomment and set if your Redis requires a password
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app/
      - /app/node_modules

volumes:
  postgres-data:
  redis-data:
